language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "pypy3"
os:
  - linux
  - osx
install:
  - pip install -r requirements-dev.txt
script:
  - python tests/test_all.py
jobs:
  allow_failures:
    - os: osx